<div style="text-align: center;">
    <h1><strong>Alma Mater Studiorum - University of Bologna</strong></h1>
    

<div style="display:flex; justify-content:center; align-items:center; padding:5px;">
        <img src="../images_reports/image.png" style="height:300px; width:auto">
    </div>

<h2><strong>Cybersecurity</strong></h2>

<h3><strong>PROYECT</strong><br>
    <strong>Attacker Behavioral Profiling in SSH honeypots.</strong></h3>

<p><strong>STUDENTS</strong></p>
    <ul style="list-style-type:none; padding: 0;">
        <li><strong>Rubén Gil Martínez<strong></li>
        <li><strong>Guillermo López Pérez<strong></li>
        <li><strong>Jorge Mejías Donoso<strong></li>
    </ul>
</div>

- ### **Research question:**

**Can machine learning models accurately classify attackers into distinct behavioral**
**profiles (automated bots, script kiddies, skilled operators) based on their command**
**sequences and interaction patterns in SSH honeypots?**

## **2) Unsupervised Approach: Clustering by means of a evolution of DBSCAN to obtain the different types of attackers**

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# ==========================
# 1) Cargar dataset
# ==========================
final_dataset = pd.read_csv("../DATASETS/attacker_behavioral_profiles_dataset_2.0.csv", index_col="session_id")
df = final_dataset.copy()

# Guardar el índice (session_id)
session_ids = df.index

# ==========================
# 2) Preprocesado (escalado)
# ==========================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

# ==========================
# 3) K-Means con k = 3
# ==========================
k = 3
kmeans = KMeans(n_clusters=k, random_state=42)

cluster_labels = kmeans.fit_predict(X_scaled)

# Añadir los clusters al dataset
df["cluster"] = cluster_labels

# ==========================
# 4) Mostrar resultados
# ==========================
print("Distribución de clusters:")
print(df["cluster"].value_counts())

df.head(10)

ValueError: Input X contains NaN.
KMeans does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [2]:
df.head(10)

,num_events,num_commands,session_duration,mean_inter_command_time,std_inter_command_time,command_error_rate,file_transfer_ratio,recon_exploit_ratio,login_error_rate,unique_commands_ratio,command_diversity
session_id,,,,,,,,,,,
00081b571122,78.0,23.0,31.249671,1.160163,1.173813,0.086957,0.173913,0.400000,0.0,0.538462,19.0
0076d693f7fd,78.0,23.0,32.132288,1.194688,1.211933,0.086957,0.173913,0.400000,0.0,0.538462,19.0
00aa3ae5d33a,78.0,23.0,36.995369,1.388428,1.529704,0.086957,0.173913,0.400000,0.0,0.538462,19.0
010ad96c3f21,16.0,7.0,68.448152,3.257964,7.958238,0.428571,0.000000,0.000000,0.0,0.285714,6.0
012f382592c2,78.0,23.0,6.000740,0.201693,0.094307,0.086957,0.173913,0.400000,0.0,0.538462,19.0
01310728d909,21.0,9.0,17.792190,1.240789,0.217969,0.000000,0.000000,1.999998,0.0,0.500000,11.0
0148a3eded81,79.0,23.0,47.535764,1.794312,1.813615,0.086957,0.217391,0.333333,0.0,0.538462,19.0
018dc4a4b877,41.0,19.0,12.066789,0.448912,0.102372,0.000000,0.000000,1.999998,0.0,0.558824,16.0
01da6910d207,41.0,19.0,25.455374,1.026140,0.116896,0.000000,0.000000,1.999998,0.0,0.558824,16.0
01efe494fcc0,16.0,7.0,68.608636,3.242624,7.927324,0.428571,0.000000,0.000000,0.0,0.285714,6.0

In [46]:
final_dataset.head(20)

,num_events,num_commands,session_duration,mean_inter_command_time,std_inter_command_time,error_rate,file_transfer_ratio,recon_exploit_ratio,unique_commands_ratio,command_diversity
session_id,,,,,,,,,,
00081b571122,78.0,23.0,31.249671,0.405840,0.725227,0.086957,0.173913,0.400000,0.538462,19.0
0076d693f7fd,78.0,23.0,32.132288,0.417302,0.746186,0.086957,0.173913,0.400000,0.538462,19.0
00aa3ae5d33a,78.0,23.0,36.995369,0.480459,0.921394,0.086957,0.173913,0.400000,0.538462,19.0
010ad96c3f21,16.0,7.0,68.448152,4.563210,8.109452,0.428571,0.000000,0.000000,0.285714,6.0
012f382592c2,78.0,23.0,6.000740,0.077932,0.175830,0.086957,0.173913,0.400000,0.538462,19.0
01310728d909,21.0,9.0,17.792190,0.889610,0.949542,0.000000,0.000000,1.999998,0.500000,11.0
0148a3eded81,79.0,23.0,47.535764,0.609433,1.133830,0.086957,0.217391,0.333333,0.538462,19.0
018dc4a4b877,41.0,19.0,12.066789,0.301670,0.361576,0.000000,0.000000,1.999998,0.558824,16.0
01da6910d207,41.0,19.0,25.455374,0.636384,0.525615,0.000000,0.000000,1.999998,0.558824,16.0
01efe494fcc0,16.0,7.0,68.608636,4.573909,8.119779,0.428571,0.000000,0.000000,0.285714,6.0
02125b4ced9a,41.0,19.0,29.965278,0.749132,0.700162,0.000000,0.000000,1.999998,0.558824,16.0
024821112d32,78.0,23.0,10.350692,0.134425,0.241072,0.086957,0.173913,0.400000,0.538462,19.0
0263a6b216dd,77.0,23.0,42.055636,0.553364,1.014935,0.086957,0.130435,0.500000,0.538462,19.0
028532e63dc0,41.0,19.0,25.048949,0.626224,0.454087,0.000000,0.000000,1.999998,0.558824,16.0
029fbd9f9f17,78.0,23.0,8.615960,0.111896,0.278302,0.086957,0.173913,0.400000,0.538462,19.0
02a7e70ddb65,41.0,19.0,14.076870,0.351922,0.387946,0.000000,0.000000,1.999998,0.558824,16.0
02c1bec458bd,78.0,23.0,6.770280,0.087926,0.184165,0.086957,0.173913,0.400000,0.538462,19.0
02c2ce40e41c,16.0,7.0,68.342209,4.556147,8.116181,0.428571,0.000000,0.000000,0.285714,6.0
02c6e6f553b8,77.0,23.0,26.339137,0.346568,0.615458,0.086957,0.130435,0.500000,0.538462,19.0
02def60df830,78.0,23.0,5.797791,0.075296,0.171934,0.086957,0.173913,0.400000,0.538462,19.0

In [60]:
bot_sample = final_dataset.loc['ffbf6704050d']
sk_sample = final_dataset.loc['01efe494fcc0']
pro_sample = final_dataset.loc['01310728d909']

In [72]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from scipy.spatial.distance import cdist

# ==============================
# 1) Dataset y samples
# ==============================
df = final_dataset.copy()
samples = {
    'bot': df.loc['ffbf6704050d'],
    'sk': df.loc['01efe494fcc0'],
    'pro': df.loc['01310728d909']
}

# ==============================
# 2) Escalado
# ==============================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)
samples_scaled = {k: scaler.transform(v.values.reshape(1, -1))[0] for k, v in samples.items()}

# ==============================
# 3) Calcular distancias y asignar label
# ==============================
labels = []
for x in X_scaled:
    dists = {label: np.linalg.norm(x - s) for label, s in samples_scaled.items()}
    nearest_label = min(dists, key=dists.get)
    labels.append(nearest_label)

df['label'] = labels

# ==============================
# 4) Resultados
# ==============================
print(df['label'].value_counts())
print(df.head(10))

label
bot    1663
sk      169
pro     110
Name: count, dtype: int64
              num_events  num_commands  session_duration  \
session_id
00081b571122        78.0          23.0         31.249671
0076d693f7fd        78.0          23.0         32.132288
00aa3ae5d33a        78.0          23.0         36.995369
010ad96c3f21        16.0           7.0         68.448152
012f382592c2        78.0          23.0          6.000740
01310728d909        21.0           9.0         17.792190
0148a3eded81        79.0          23.0         47.535764
018dc4a4b877        41.0          19.0         12.066789
01da6910d207        41.0          19.0         25.455374
01efe494fcc0        16.0           7.0         68.608636

              mean_inter_command_time  std_inter_command_time  error_rate  \
session_id
00081b571122                 0.405840                0.725227    0.086957
0076d693f7fd                 0.417302                0.746186    0.086957
00aa3ae5d33a                 0.480459                0.921394    0.086957
010ad96c3f21                 4.563210                8.109452    0.428571
012f382592c2                 0.077932                0.175830    0.086957
01310728d909                 0.889610                0.949542    0.000000
0148a3eded81                 0.609433                1.133830    0.086957
018dc4a4b877                 0.301670                0.361576    0.000000
01da6910d207                 0.636384                0.525615    0.000000
01efe494fcc0                 4.573909                8.119779    0.428571

              file_transfer_ratio  recon_exploit_ratio  unique_commands_ratio  \
session_id
00081b571122             0.173913             0.400000               0.538462
0076d693f7fd             0.173913             0.400000               0.538462
00aa3ae5d33a             0.173913             0.400000               0.538462
010ad96c3f21             0.000000             0.000000               0.285714
012f382592c2             0.173913             0.400000               0.538462
01310728d909             0.000000             1.999998               0.500000
0148a3eded81             0.217391             0.333333               0.538462
018dc4a4b877             0.000000             1.999998               0.558824
01da6910d207             0.000000             1.999998               0.558824
01efe494fcc0             0.000000             0.000000               0.285714

              command_diversity label
session_id
00081b571122               19.0   bot
0076d693f7fd               19.0   bot
00aa3ae5d33a               19.0   bot
010ad96c3f21                6.0    sk
012f382592c2               19.0   bot
01310728d909               11.0   pro
0148a3eded81               19.0   bot
018dc4a4b877               16.0   bot
01da6910d207               16.0   bot
01efe494fcc0                6.0    sk

c:\Users\Guille\anaconda3\envs\mi_entorno\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\Guille\anaconda3\envs\mi_entorno\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\Guille\anaconda3\envs\mi_entorno\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [90]:
df

,num_events,num_commands,session_duration,mean_inter_command_time,std_inter_command_time,command_error_rate,file_transfer_ratio,recon_exploit_ratio,login_error_rate,unique_commands_ratio,command_diversity
session_id,,,,,,,,,,,
00081b571122,78.0,23.0,31.249671,1.160163,1.173813,0.086957,0.173913,0.400000,0.0,0.538462,19.0
0076d693f7fd,78.0,23.0,32.132288,1.194688,1.211933,0.086957,0.173913,0.400000,0.0,0.538462,19.0
00aa3ae5d33a,78.0,23.0,36.995369,1.388428,1.529704,0.086957,0.173913,0.400000,0.0,0.538462,19.0
010ad96c3f21,16.0,7.0,68.448152,3.257964,7.958238,0.428571,0.000000,0.000000,0.0,0.285714,6.0
012f382592c2,78.0,23.0,6.000740,0.201693,0.094307,0.086957,0.173913,0.400000,0.0,0.538462,19.0
...,...,...,...,...,...,...,...,...,...,...,...
ff88bb2a4976,78.0,23.0,15.164849,0.551371,0.478581,0.086957,0.173913,0.400000,0.0,0.538462,19.0
ff961e5a8d10,41.0,19.0,30.582356,1.315240,1.329285,0.000000,0.000000,1.999998,0.0,0.558824,16.0
ffa90519d8a6,78.0,23.0,6.479960,0.220048,0.125762,0.086957,0.173913,0.400000,0.0,0.538462,19.0
ffc067419633,78.0,23.0,18.845538,0.688483,0.634182,0.086957,0.173913,0.400000,0.0,0.538462,19.0
fffb88427f4c,41.0,19.0,4.494230,0.146758,0.032893,0.000000,0.000000,1.999998,0.0,0.558824,16.0

In [76]:
df = pd.read_csv("../attacker_behavioral_profiles_dataset.csv")

In [78]:
df.index = df['session_id']

In [81]:
df.drop(columns=['session_id'], inplace=True)

In [91]:
df_reduced = df[['num_commands', 'session_duration', 'mean_inter_command_time', 'std_inter_command_time', 'command_error_rate']]

In [135]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN

# ==========================
# 1) Copiar dataset y eliminar NaN
# ==========================
df_clean = df.dropna()  # elimina filas con cualquier NaN
print(f"Filas antes: {len(df)}, filas después de dropna: {len(df_clean)}")

# ==========================
# 2) Escalar los datos
# ==========================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_clean)

# ==========================
# 3) Aplicar DBSCAN
# ==========================
dbscan = DBSCAN(eps=2, min_samples=15)
clusters = dbscan.fit_predict(X_scaled)

# ==========================
# 4) Añadir cluster al DataFrame limpio
# ==========================
df_clean['cluster'] = clusters

# ==========================
# 5) Resultados
# ==========================
print("Número de clusters encontrados (excluyendo ruido):", len(set(clusters)) - (1 if -1 in clusters else 0))
print(df_clean['cluster'].value_counts())
print(df_clean.head(10))

Filas antes: 3998, filas después de dropna: 3971
Número de clusters encontrados (excluyendo ruido): 8
cluster
 0    2707
 2     811
 3     135
-1      95
 4      80
 1      59
 6      51
 7      17
 5      16
Name: count, dtype: int64
              num_events  num_commands  session_duration  \
session_id
00081b571122        78.0          23.0         31.249671
0076d693f7fd        78.0          23.0         32.132288
00aa3ae5d33a        78.0          23.0         36.995369
010ad96c3f21        16.0           7.0         68.448152
012f382592c2        78.0          23.0          6.000740
01310728d909        21.0           9.0         17.792190
0148a3eded81        79.0          23.0         47.535764
018dc4a4b877        41.0          19.0         12.066789
01da6910d207        41.0          19.0         25.455374
01efe494fcc0        16.0           7.0         68.608636

              mean_inter_command_time  std_inter_command_time  \
session_id
00081b571122                 1.160163                1.173813
0076d693f7fd                 1.194688                1.211933
00aa3ae5d33a                 1.388428                1.529704
010ad96c3f21                 3.257964                7.958238
012f382592c2                 0.201693                0.094307
01310728d909                 1.240789                0.217969
0148a3eded81                 1.794312                1.813615
018dc4a4b877                 0.448912                0.102372
01da6910d207                 1.026140                0.116896
01efe494fcc0                 3.242624                7.927324

              command_error_rate  file_transfer_ratio  recon_exploit_ratio  \
session_id
00081b571122            0.086957             0.173913             0.400000
0076d693f7fd            0.086957             0.173913             0.400000
00aa3ae5d33a            0.086957             0.173913             0.400000
010ad96c3f21            0.428571             0.000000             0.000000
012f382592c2            0.086957             0.173913             0.400000
01310728d909            0.000000             0.000000             1.999998
0148a3eded81            0.086957             0.217391             0.333333
018dc4a4b877            0.000000             0.000000             1.999998
01da6910d207            0.000000             0.000000             1.999998
01efe494fcc0            0.428571             0.000000             0.000000

              login_error_rate  unique_commands_ratio  command_diversity  \
session_id
00081b571122               0.0               0.538462               19.0
0076d693f7fd               0.0               0.538462               19.0
00aa3ae5d33a               0.0               0.538462               19.0
010ad96c3f21               0.0               0.285714                6.0
012f382592c2               0.0               0.538462               19.0
01310728d909               0.0               0.500000               11.0
0148a3eded81               0.0               0.538462               19.0
018dc4a4b877               0.0               0.558824               16.0
01da6910d207               0.0               0.558824               16.0
01efe494fcc0               0.0               0.285714                6.0

              cluster
session_id
00081b571122        0
0076d693f7fd        0
00aa3ae5d33a        0
010ad96c3f21        1
012f382592c2        0
01310728d909       -1
0148a3eded81        0
018dc4a4b877        2
01da6910d207        2
01efe494fcc0        1

C:\Users\Guille\AppData\Local\Temp\ipykernel_10712\1735156482.py:26: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [137]:
import plotly.graph_objects as go
from sklearn.decomposition import PCA
import numpy as np

# ==========================
# 1) PCA con 3 componentes
# ==========================
pca = PCA(n_components=3)
X_pca = pca.fit_transform(X_scaled)

# ==========================
# 2) Preparar clusters
# ==========================
clusters = df_clean['cluster'].values
unique_clusters = np.unique(clusters)

# ==========================
# 3) Crear figura interactiva
# ==========================
fig = go.Figure()

colors = ['red', 'blue', 'green', 'orange', 'purple', 'brown', 'pink', 'gray', 'cyan', 'magenta']

for i, cluster in enumerate(unique_clusters):
    cluster_mask = clusters == cluster
    label = f"Cluster {cluster}" if cluster != -1 else "Noise"
    fig.add_trace(go.Scatter3d(
        x=X_pca[cluster_mask, 0],
        y=X_pca[cluster_mask, 1],
        z=X_pca[cluster_mask, 2],
        mode='markers',
        marker=dict(
            size=5,
            color=colors[i % len(colors)],
            opacity=0.8
        ),
        name=label
    ))

# ==========================
# 4) Configuración de layout
# ==========================
fig.update_layout(
    title="DBSCAN Clusters (PCA 3D Interactivo)",
    scene=dict(
        xaxis_title='PCA 1',
        yaxis_title='PCA 2',
        zaxis_title='PCA 3'
    ),
    width=800,
    height=600
)

# ==========================
# 5) Mostrar figura
# ==========================
fig.show()

In [147]:
df_clean[df_clean['cluster'] == -1]

,num_events,num_commands,session_duration,mean_inter_command_time,std_inter_command_time,command_error_rate,file_transfer_ratio,recon_exploit_ratio,login_error_rate,unique_commands_ratio,command_diversity,cluster
session_id,,,,,,,,,,,,
01310728d909,21.0,9.0,17.792190,1.240789,0.217969,0.000000,0.000000,1.999998,0.000000,0.500000,11.0,-1
051da2977a31,41.0,19.0,135.831325,5.914595,11.830356,0.000000,0.000000,1.999998,0.000000,0.558824,16.0,-1
05b4b4baeca0,78.0,23.0,128.298447,4.396312,5.476454,0.086957,0.173913,0.400000,0.000000,0.538462,19.0,-1
0accce635ce5,48.0,14.0,17.131963,0.900577,0.271887,0.214286,0.000000,1.999998,0.000000,0.333333,17.0,-1
0f7ac69e1dff,24.0,10.0,4.398631,0.087439,0.074411,0.300000,0.000000,5.999994,0.857143,0.153846,12.0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...
e7b8916e65fe,7.0,1.0,181.590219,0.000000,0.000000,0.000000,0.000000,1.999998,0.000000,1.000000,1.0,-1
ea3af5d51271,21.0,8.0,139.885230,0.782645,0.056128,0.000000,0.000000,1.999998,0.000000,0.363636,8.0,-1
f090ec8ba058,78.0,23.0,112.022654,4.848084,5.849825,0.086957,0.173913,0.400000,0.000000,0.538462,19.0,-1
f0c878337c61,21.0,8.0,150.884271,0.636715,0.006544,0.000000,0.000000,1.999998,0.000000,0.363636,8.0,-1
fb2ddc958342,20.0,10.0,2.376559,0.083450,0.072906,0.300000,0.000000,1.999998,0.666666,0.153846,12.0,-1